name: Test input

on:
  workflow_dispatch:
    inputs:
      build-rabbit:
        description: "Do you want to build rabbit?"
        type: boolean
        required: false
        default: "false"

jobs:
  print-job:
    runs-on: ubuntu-latest
    if: ${{ inputs.build-rabbit }}
    steps:
      - name: Print Message
        run: |
          echo "Input received: ${{ inputs.build-rabbit }}"
