on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go: [ '1.14' ]
    name: Go ${{ matrix.go }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Get slack-go API
        run: go get -u github.com/slack-go/slack
      - run: go run send-reminder.go
