name: test matrix

on:
  workflow_dispatch:

jobs:
  example_matrix:
    strategy:
      matrix:
        os: [test1, test2]
    runs-on: ubuntu-latest
    steps:
      - name: test
        shell: bash
        run: |
          echo ${{ matrix.os }}

  example_matrix_2:
    needs: example_matrix
    runs-on: ubuntu-latest
    steps:
      - name: test
        shell: bash
        run: |
          echo ${{ matrix.os }}
